name: transport
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pot
  - biopython=1.78
  - pillow
  - statsmodels
  - numpy
  - pandas
  - scipy
  - requests
  - pip:
    - pygtrie==2.4.2
    - seqmagick==0.8.4
